export type Grade = 9 | 10 | 11 | 12;
export type Subject = "mathematics" | "english" | "science" | "socialStudies" | "studySkills";
export type ActivityKind = "lesson" | "reading" | "quiz" | "test" | "reflection";
export type Question = { prompt: string; hint: string; options: string[]; answer: number; explanation: string };
export type Resource = { id: string; title: string; type: "guide" | "reference" | "template" | "checklist"; subject: Subject | "all"; description: string; content: string[] };
export type LearningContent = { intro: string; bullets: string[]; example?: string; passage?: string; resources: string[] };
export type Activity = { id: string; week: number; title: string; subtitle: string; subject: Subject; kind: ActivityKind; minutes: number; points: number; icon: string; questions: Question[]; content: LearningContent };
export type Week = { id: number; label: string; title: string; detail: string; milestone: string; ids: string[] };
export type CurriculumProgram = { grade: Grade; previousGrade: number | null; nextGrade: number | null; activities: Activity[]; weeks: Week[]; resources: Resource[]; contentFor: (activity: Activity) => LearningContent };

export const grades = [9, 10, 11, 12] as const;
export const subjects: { id: Subject; label: string; short: string }[] = [
  { id: "mathematics", label: "Mathematics", short: "Math" },
  { id: "english", label: "English", short: "English" },
  { id: "science", label: "Science", short: "Science" },
  { id: "socialStudies", label: "Canadian & social studies", short: "Social studies" },
  { id: "studySkills", label: "Study systems", short: "Study skills" },
];

const q = (prompt: string, hint: string, options: string[], answer: number, explanation: string): Question => ({ prompt, hint, options, answer, explanation });
const gradeInfo: Record<Grade, { previous: number | null; next: number | null; focus: string }> = {
  9: { previous: 8, next: 10, focus: "secondary foundations, quantitative reasoning, literacy, and study independence" },
  10: { previous: 9, next: 11, focus: "core secondary concepts, evidence, problem solving, and course-pathway choices" },
  11: { previous: 10, next: 12, focus: "destination-related thinking, research, analysis, and independent application" },
  12: { previous: 11, next: null, focus: "final-credit readiness, literacy, capstone work, and post-secondary transition skills" },
};

const subjectData: Record<Subject, { titles: string[]; subtitles: string[]; intros: string[]; bullets: string[][]; examples: string[]; passages: string[]; questions: Question[] }> = {
  mathematics: {
    titles: ["Quantitative reset", "Algebra in context", "Data, models & decisions", "Next-step mathematics"],
    subtitles: ["Rebuild the number sense that secondary math depends on", "Use equations, functions, and representations to explain change", "Interpret data, probability, and financial choices", "Preview the reasoning expected in the next course"],
    intros: ["Mathematics is not a list of tricks. It is a language for describing relationships, testing assumptions, and making decisions.", "A strong algebra solution shows what the variables mean, why the operation is valid, and whether the result fits the situation.", "Data can support a decision without proving a perfect answer. Read the scale, sample, uncertainty, and context before drawing a conclusion.", "The goal is transfer: use a familiar idea in a less familiar situation, then explain your reasoning clearly."],
    bullets: [["Translate words into quantities and units.", "Estimate before calculating so errors are visible.", "Keep a mistake log with the exact step that broke down."], ["Define variables before manipulating an equation.", "Use a table, graph, or equation to check the same relationship.", "State restrictions when a model cannot apply."], ["Distinguish correlation from causation.", "Compare percentages with the correct base.", "Use proportional reasoning for budgets and trade-offs."], ["Annotate the prompt before choosing a formula.", "Show a complete chain of reasoning.", "Check your answer using a second representation."]],
    examples: ["If a taxi costs $4 plus $2 per kilometre, the model is C = 4 + 2d. The 4 is the fixed cost; 2 is the rate.", "For 3x − 7 = 14, add 7 first, then divide by 3: x = 7. Check: 21 − 7 = 14.", "A 20% increase followed by a 20% decrease does not return to the starting value: 1.20 × 0.80 = 0.96.", "When a formula is unfamiliar, identify the quantities, units, and relationship before substituting values."],
    passages: ["A city is comparing two transit passes. Pass A costs $95 monthly. Pass B costs $2.75 per ride. The right choice depends on the number of rides, not on which price sounds smaller.", "A student models savings with a starting balance and a weekly deposit. The model becomes useful only when the student states the time period and what is being ignored.", "A survey reports that 64% of respondents support a proposal. Before treating that as a verdict, ask who was surveyed, how many people responded, and how the question was worded.", "Course pathways use mathematical reasoning in different ways. The transferable skill is not memorizing one formula; it is selecting and defending a method."],
    questions: [q("A line has rate 3 and initial value 5. Which equation represents it?", "Use y = mx + b.", ["y = 5x + 3", "y = 3x + 5", "y = 3x − 5"], 1, "The rate is m = 3 and the initial value is b = 5."), q("A $120 item is discounted by 25%. What is the sale price?", "Find 75% of the original price.", ["$30", "$90", "$95"], 1, "A 25% discount leaves 75%: 0.75 × 120 = 90."), q("Which is the best first move when a result seems impossible?", "Good mathematicians investigate.", ["Check assumptions, units, and the calculation", "Delete the result", "Round until it looks right"], 0, "A result needs to be checked, not hidden.")],
  },
  english: {
    titles: ["Read for meaning", "Argument & evidence", "Research and synthesis", "Write with control"],
    subtitles: ["Move from summary to interpretation", "Build claims that a reader can test", "Compare sources and combine ideas responsibly", "Revise for clarity, voice, structure, and precision"],
    intros: ["Strong reading is active. Notice what a text says, how it says it, what it leaves out, and what the choices suggest.", "An argument becomes credible when its claim, evidence, reasoning, and limits are visible to the reader.", "Research is more than collecting links. It is selecting trustworthy sources, recording context, and making your own synthesis.", "Good writing is built in passes: purpose, structure, evidence, sentences, then proofreading. Revision is not a punishment; it is the work."],
    bullets: [["Annotate one claim, one craft choice, and one question.", "Separate what the text states from what you infer.", "Use a short quotation only when you can explain it."], ["Write a claim narrow enough to defend.", "Explain how each piece of evidence supports the claim.", "Acknowledge a reasonable limitation or counterargument."], ["Record creator, date, audience, purpose, and perspective.", "Paraphrase accurately instead of copying.", "Synthesize patterns across sources, not just source-by-source summaries."], ["Read the draft aloud once.", "Replace vague verbs with precise ones.", "Check that every paragraph earns its place."],
    ],
    examples: ["Instead of saying a character is brave, point to the decision they make under pressure and explain what it reveals.", "Claim: the policy improves access. Evidence: the report shows a 14% increase. Reasoning: the change matters because access was measured before and after the policy.", "A source map prevents accidental plagiarism: note the idea, your paraphrase, the exact source, and the date you accessed it.", "Revision example: 'The result was good' becomes 'The revised design reduced heat loss during the overnight test.'"],
    passages: ["A school newspaper reports that students want later library hours. The strongest article does not stop at a poll; it identifies who responded, quotes different experiences, and explains what the change would require.", "A writer can sound certain while using weak evidence. Read for the gap between the confidence of the language and the quality of the support.", "Two sources may describe the same event differently because they have different audiences and purposes. That difference is evidence to analyse, not a reason to choose the louder source.", "A final draft should let a reader follow the thinking without needing the writer in the room to explain it."],
    questions: [q("Which evidence best supports a claim about a text?", "Evidence should be specific and traceable.", ["A precise passage or detail from the text", "A reaction unrelated to the text", "A guess about the author's life"], 0, "Specific textual evidence lets a reader verify your reasoning."), q("What makes a thesis useful?", "A thesis gives the writing direction.", ["It makes a focused, arguable claim", "It repeats the assignment", "It includes every detail"], 0, "A focused claim can organize a whole piece of writing."), q("Why acknowledge a counterargument?", "Think about credibility.", ["It shows you have tested the limits of your position", "It makes evidence unnecessary", "It guarantees agreement"], 0, "Acknowledging a reasonable limit strengthens trust.")],
  },
  science: {
    titles: ["Scientific thinking", "Systems & change", "Evidence and uncertainty", "Applied science preview"],
    subtitles: ["Design fair investigations and read results", "Explain matter, energy, cells, and systems through models", "Interpret measurements without overstating the conclusion", "Connect concepts to current Canadian contexts"],
    intros: ["Science starts with a question that can be investigated. A good method makes the evidence useful and the limits visible.", "Models are tools, not reality. They help explain a system while leaving some details out.", "A measurement is stronger when you know its units, precision, source, and uncertainty.", "Applied science asks what a concept means outside the worksheet: in health, climate, technology, or community decisions."],
    bullets: [["Identify the variable you change and the response you measure.", "Keep relevant conditions consistent.", "Write a conclusion that matches the evidence."], ["Use a labelled model to show relationships.", "Explain energy or matter moving through a system.", "Say what the model cannot show."], ["Separate observation from interpretation.", "Use repeated trials when possible.", "Avoid claiming more than the design can support."], ["Connect a concept to a real decision.", "Name benefits, risks, and trade-offs.", "Use a credible source for current facts."]],
    examples: ["In a plant investigation, light level is the independent variable and measured growth is the dependent variable.", "A food-web model shows energy transfer, but it does not capture every interaction in an ecosystem.", "A mean can describe a sample while still hiding outliers. Report the spread when it matters.", "A technology may reduce one environmental impact while increasing another; analyse the full system."],
    passages: ["A lab group changes both water temperature and the amount of salt. If the solution dissolves faster, the group cannot tell which change caused the result.", "A model of carbon movement helps students see reservoirs and transfers. Its value depends on the question it is being used to answer.", "A headline says a treatment 'works for everyone.' The underlying study included 42 participants. The claim deserves a closer look at sample and design.", "Science literacy includes asking what evidence would change your mind and what information is still missing."],
    questions: [q("What is a dependent variable?", "It is the response you measure.", ["The factor you change", "The factor you measure", "A factor you ignore"], 1, "The dependent variable responds to the independent variable."), q("Why are controlled variables important?", "Think about fair comparisons.", ["They help isolate the effect of the factor being tested", "They make experiments faster", "They replace measurements"], 0, "Keeping relevant factors stable makes comparisons meaningful."), q("What should a conclusion do?", "Return to the evidence.", ["State whether the evidence supports the claim and why", "Introduce an unrelated topic", "Promise the result is universal"], 0, "A careful conclusion stays proportional to the evidence.")],
  },
  socialStudies: {
    titles: ["Canada in context", "Power and perspective", "Civic choices", "Contemporary issues"],
    subtitles: ["Read Canadian history and geography as connected systems", "Analyse who benefits, who is missing, and why", "Evaluate policy choices with evidence and trade-offs", "Build informed opinions about issues that affect communities"],
    intros: ["Social studies asks how people, place, institutions, and decisions shape one another. Context turns a fact into understanding.", "A source has a creator, audience, purpose, and perspective. Naming those features is the beginning of analysis.", "A civic recommendation should be evidence-informed and practical, not just a personal preference.", "Current issues are complex because values and consequences are distributed unevenly. Good reasoning can hold that complexity."],
    bullets: [["Place events on a timeline and map.", "Distinguish primary from secondary evidence.", "Ask whose experience the record centres."], ["Identify perspective without dismissing the evidence.", "Compare sources that disagree.", "Use precise historical language."], ["Name stakeholders and likely consequences.", "Separate a value judgement from an empirical claim.", "Recommend a next step that could actually be implemented."], ["Check a current source's date and method.", "Look for Canadian and local context.", "Revise your view when stronger evidence appears."]],
    examples: ["A map is not neutral: its scale, boundaries, labels, and omissions shape what the reader notices.", "A strong source analysis identifies what the creator could know, what they wanted the audience to believe, and what the source cannot show.", "A policy brief can recommend a change while naming cost, implementation, and unintended effects.", "Two people can value the same outcome but disagree about the best route because they weigh risks differently."],
    passages: ["A municipal proposal adds a protected bike lane. Students compare the map, traffic data, resident comments, and budget before writing a recommendation.", "A historical photograph shows one moment, not the whole experience of the people pictured. Captions, provenance, and missing voices matter.", "A public consultation may hear from people with time and internet access more easily than from people who work evenings. Participation data needs context.", "Being informed does not mean having a hot take on every issue. It means knowing what you know, what you do not, and how to investigate next."],
    questions: [q("Why identify a source's creator and audience?", "Context changes meaning.", ["To understand perspective and purpose", "To avoid reading the source", "To prove the source is always wrong"], 0, "Creator, audience, and purpose help you interpret a source."), q("What is a stakeholder?", "Think about who is affected.", ["A person or group affected by a decision", "A historical date", "A map scale"], 0, "Stakeholders have interests or are affected by outcomes."), q("What makes a policy recommendation useful?", "A recommendation must work in the real world.", ["It connects evidence, goals, and practical constraints", "It lists only a personal preference", "It ignores unintended effects"], 0, "Workable recommendations account for evidence and constraints.")],
  },
  studySkills: {
    titles: ["Build your study system", "Focus and retrieval", "Mistakes into progress", "Independent launch plan"],
    subtitles: ["Set up a realistic two-month rhythm", "Remember more with shorter, focused sessions", "Use feedback instead of waiting for motivation", "Leave with a plan you can run without a parent beside you"],
    intros: ["Independence is designed. A simple plan, clear next step, and reliable help path make it easier to begin on low-motivation days.", "Learning sticks when you retrieve, explain, and space practice instead of only rereading.", "A mistake is useful when it tells you what to practise, what resource to use, and when to try again.", "The best summer result is not an overloaded schedule. It is a repeatable learning system you can carry into the school year."],
    bullets: [["Choose a consistent start window.", "Keep one visible next action.", "Use a 45–75 minute daily learning cap."], ["Study in 20–25 minute focus blocks.", "Close notes and recall before checking.", "Take a real movement break between blocks."], ["Label the gap: concept, process, reading, or attention.", "Use the built-in hint, example, or glossary.", "Retry once and record the corrected method."], ["Plan the next seven days before finishing week eight.", "Protect sleep, movement, meals, and offline time.", "Ask a teacher or trusted adult when the issue is beyond the resource library."]],
    examples: ["A 60-minute session: 5 minutes plan, 25 minutes lesson, 10 minutes break, 15 minutes retrieval, 5 minutes next-step note.", "Before revealing an answer, write what you remember and where your reasoning became uncertain.", "Mistake log: 'I divided before isolating the variable. Next time I will underline the operation affecting x.'", "A sustainable plan has a minimum version for difficult days: one reading, three questions, and a next-step note."],
    passages: ["A student who waits to feel motivated loses the first decision. A student who opens the plan and does the first 10 minutes gives motivation a chance to arrive after starting.", "Rereading feels fluent because the page looks familiar. Retrieval is harder, but the effort shows what you actually know.", "A useful help system does not pretend every learner should work alone. It helps them identify the exact question to bring to a teacher, tutor, or trusted adult.", "Your summer plan should leave room for friends, outdoor time, sleep, and boredom. Learning is one part of a healthy life, not the whole life."],
    questions: [q("Which study plan is most sustainable?", "Think consistency, not cramming.", ["Short, focused sessions with retrieval and breaks", "One all-nighter", "Rereading without testing yourself"], 0, "Spaced practice with retrieval is easier to sustain and remember."), q("What should you do when stuck?", "Use a sequence.", ["Name the gap, consult a resource, then try again", "Wait indefinitely", "Skip all hard work"], 0, "Breaking the problem down makes help usable."), q("Why track mistakes?", "Mistakes are information.", ["They reveal what to practise next", "They prove you cannot learn", "They replace feedback"], 0, "A mistake log turns errors into a targeted plan.")],
  },
};

function activity(subject: Subject, grade: Grade, index: number, week: number, kind: ActivityKind, minutes: number, points: number): Activity {
  const data = subjectData[subject];
  const slot = (grade + index) % data.titles.length;
  const content: LearningContent = { intro: data.intros[slot], bullets: data.bullets[slot], example: data.examples[slot], passage: data.passages[slot], resources: [`${subject}-guide`, "study-system", "help-path"] };
  const questions = data.questions.map((item, questionIndex) => ({ ...item, prompt: questionIndex === 0 && kind === "test" ? `${item.prompt} Explain your reasoning after choosing.` : item.prompt }));
  return { id: `${grade}-w${week}-${subject}-${index}-${kind}`, week, title: data.titles[slot], subtitle: data.subtitles[slot], subject, kind, minutes, points, icon: subject === "mathematics" ? "∑" : subject === "english" ? "Aa" : subject === "science" ? "◌" : subject === "socialStudies" ? "◎" : "⌁", questions: kind === "quiz" || kind === "test" ? questions : questions.slice(0, 1), content };
}

export function getProgram(grade: Grade): CurriculumProgram {
  const previousGrade = gradeInfo[grade].previous;
  const nextGrade = gradeInfo[grade].next;
  const activities: Activity[] = [
    activity("studySkills", grade, 0, 1, "lesson", 20, 30),
    activity("mathematics", grade, 0, 1, "reading", 25, 40),
    activity("english", grade, 0, 1, "reading", 25, 40),
    activity("mathematics", grade, 1, 2, "lesson", 30, 50),
    activity("english", grade, 1, 2, "lesson", 30, 50),
    activity("science", grade, 0, 3, "reading", 30, 50),
    activity("socialStudies", grade, 0, 3, "reading", 30, 50),
    activity("mathematics", grade, 2, 4, "test", 40, 80),
    activity("english", grade, 2, 4, "quiz", 30, 60),
    activity("science", grade, 1, 5, "lesson", 30, 50),
    activity("socialStudies", grade, 1, 5, "lesson", 30, 50),
    activity("mathematics", grade, 3, 6, "lesson", 35, 55),
    activity("english", grade, 3, 6, "lesson", 35, 55),
    activity("science", grade, 2, 7, "test", 40, 80),
    activity("socialStudies", grade, 2, 7, "reflection", 30, 55),
    activity("studySkills", grade, 3, 8, "reflection", 25, 45),
    activity("english", grade, 3, 8, "test", 45, 90),
  ];
  const weekTitles = ["Baseline & rhythm", "Previous-grade review", "Core foundations", "Midpoint checkpoint", "Next-grade preview", "Applied practice", "Capstone preparation", "Final demonstration"];
  const weekDetails = ["Set up your independent study system and establish a baseline.", `Repair the ${previousGrade ? `Grade ${previousGrade}` : "previous-year"} ideas that unlock your current course.`, "Practise the concepts that carry across subjects.", "Use a checkpoint to choose what to repair, not to label yourself.", nextGrade ? `Preview the reasoning and vocabulary you will meet in Grade ${nextGrade}.` : "Preview post-secondary, workplace, and lifelong learning transitions.", "Apply ideas to realistic Canadian contexts and decisions.", "Synthesize evidence and prepare a final demonstration.", "Finish the assessment and write a plan for the first month back."];
  const milestones = ["Complete your baseline and choose a consistent start window.", "Finish two review studios and record three repair topics.", "Complete one focused block in each core subject.", "Take the checkpoint and choose two targeted retries.", "Complete one next-grade preview and one worked example.", "Use evidence in an applied response without waiting for help.", "Draft and revise your capstone response using the rubric.", "Complete the final demonstration and save your next-step plan."];
  const weeks: Week[] = weekTitles.map((title, index) => ({ id: index + 1, label: `WEEK ${index + 1}`, title, detail: weekDetails[index], milestone: milestones[index], ids: activities.filter((item) => item.week === index + 1).map((item) => item.id) }));
  const resources: Resource[] = [
    { id: "study-system", title: "The independent study system", type: "guide", subject: "all", description: "A practical plan for starting, focusing, checking, and stopping without a parent beside you.", content: ["Set a 45–75 minute cap and choose one start time.", "Use 20–25 minute focus blocks with a movement break.", "End every session by writing the next action in one sentence.", "If you are stuck after using the hint and example, write the exact question you need to ask a teacher or trusted adult."] },
    { id: "help-path", title: "When you are stuck", type: "checklist", subject: "all", description: "A calm sequence for getting unstuck instead of spiralling or quitting.", content: ["Name the gap: vocabulary, concept, process, reading, or attention.", "Re-read the worked example and use the hint.", "Try a smaller version of the problem.", "Record what you tried. Then ask a specific question through a teacher, tutor, librarian, or trusted adult."] },
    { id: "mathematics-guide", title: "Math reasoning reference", type: "reference", subject: "mathematics", description: "Variables, units, models, percent change, data, and answer-checking prompts.", content: ["Define quantities before choosing an operation.", "Write units on intermediate results.", "Estimate before calculating.", "Check with a graph, table, inverse operation, or second method."] },
    { id: "english-guide", title: "Reading, research & writing kit", type: "template", subject: "english", description: "A reusable annotation, source map, paragraph, and revision workflow.", content: ["Claim → evidence → reasoning → limitation.", "Source map: creator, date, audience, purpose, perspective, exact location.", "Paragraph: focused topic sentence, evidence, explanation, transition.", "Revision passes: purpose, structure, evidence, sentences, proofreading."] },
    { id: "science-guide", title: "Investigation and evidence guide", type: "reference", subject: "science", description: "A self-check for variables, controls, models, uncertainty, and conclusions.", content: ["Identify what changes, what responds, and what stays consistent.", "Use units and appropriate precision.", "Separate observation from interpretation.", "State the conclusion and its limits."] },
    { id: "socialStudies-guide", title: "Canadian source analysis kit", type: "template", subject: "socialStudies", description: "A source and civic decision framework for Canadian contexts.", content: ["Ask who created the source, when, for whom, and why.", "Locate the evidence and name missing voices.", "Identify stakeholders, values, benefits, costs, and unintended effects.", "Recommend a practical next step and cite your evidence."] },
  ];
  return { grade, previousGrade, nextGrade, activities, weeks, resources, contentFor: (item) => item.content };
}

export function getGradeLabel(grade: Grade) { return `Grade ${grade}`; }
export function getGradeInfo(grade: Grade) { return gradeInfo[grade]; }
export function isGrade(value: unknown): value is Grade { return grades.includes(Number(value) as Grade); }
export function getNextGrade(grade: Grade) { return gradeInfo[grade].next; }
export function getPreviousGrade(grade: Grade) { return gradeInfo[grade].previous; }
