export type Grade = 1 | 2 | 3 | 4 | 5;
export type Subject = "math" | "english";
export type ActivityKind = "lesson" | "game" | "quiz" | "test";
export type Question = { prompt: string; hint: string; options: string[]; answer: number; explanation: string };
export type LearningContent = { intro: string; bullets: string[]; example?: string; story?: string; gamePrompt?: string; gameOptions?: string[]; gameAnswer?: number };
export type Activity = { id: string; week: number; title: string; subtitle: string; subject: Subject; kind: ActivityKind; minutes: number; xp: number; color: string; icon: string; questions: Question[]; content: LearningContent };
export type Week = { id: number; label: string; title: string; detail: string; color: string; ids: string[] };
export type CurriculumProgram = { grade: Grade; activities: Activity[]; weeks: Week[]; contentFor: (activity: Activity) => LearningContent };

type Unit = { title: string; subtitle: string; color: string; icon: string; content: LearningContent; mathQuestions: Question[]; englishQuestions: Question[] };
const q = (prompt: string, hint: string, options: string[], answer: number, explanation: string): Question => ({ prompt, hint, options, answer, explanation });

const gradeOneUnits: Unit[] = [
  { title: "Counting Camp", subtitle: "Count, compare, and compose numbers to 50", color: "coral", icon: "123", content: { intro: "Numbers help us describe how many. Count objects once, compare groups, and build numbers from tens and ones.", bullets: ["Count each object once.", "A group of ten is useful.", "Compare numbers using more, fewer, or the same."], example: "14 is one ten and four ones.", gamePrompt: "Which number shows one ten and six ones?", gameOptions: ["16", "61", "10"], gameAnswer: 0 }, mathQuestions: [q("What number comes after 19?", "Count one more.", ["18", "20", "29", "10"], 1, "After 19 comes 20."), q("Which group has more: 7 apples or 4 apples?", "Compare the amounts.", ["7 apples", "4 apples", "They are equal"], 0, "7 is more than 4."), q("What is 10 + 3?", "Start with one ten and add three ones.", ["13", "30", "7"], 0, "One ten is 10; 10 + 3 = 13.")], englishQuestions: [q("Which word begins with the /m/ sound?", "Say each word aloud.", ["sun", "map", "dog"], 1, "Map begins with the /m/ sound."), q("Which sentence makes sense?", "Choose the complete thought.", ["Runs the dog.", "The dog runs.", "Dog the."], 1, "The dog runs is a complete sentence."), q("What does the cat do in the story?", "Find the action in the story.", ["It naps in the sun.", "It flies.", "It swims."], 0, "The story says the cat naps in the sun.")] },
  { title: "Shape Street", subtitle: "Sort 2-D and 3-D shapes", color: "blue", icon: "◈", content: { intro: "Shapes are all around us. Name, sort, and describe them by sides, corners, faces, and whether they slide or roll.", bullets: ["A circle has no straight sides.", "A triangle has three sides.", "Some 3-D objects roll; some slide; some do both."], example: "A cereal box is a rectangular prism." }, mathQuestions: [q("How many sides does a triangle have?", "Count the straight sides.", ["2", "3", "4"], 1, "A triangle has 3 sides."), q("Which shape has no corners?", "Think of a round shape.", ["circle", "square", "triangle"], 0, "A circle has no corners."), q("Which object can roll?", "Imagine it moving.", ["ball", "book", "box"], 0, "A ball has a curved surface and can roll.")], englishQuestions: [q("Which word rhymes with sun?", "Say the words aloud.", ["run", "cat", "bike"], 0, "Sun and run end with the same sound."), q("Which sentence has a capital at the start?", "Look at the first letter.", ["the dog ran.", "The dog ran.", "the Dog ran."], 1, "A sentence begins with a capital letter."), q("Which word describes a round ball?", "Choose a describing word.", ["blue", "jump", "quickly"], 0, "Blue is a describing word in this example.")] },
  { title: "Measure Market", subtitle: "Compare length, time, and simple money", color: "gold", icon: "▣", content: { intro: "Measurement and money help us make choices. Compare objects, read simple times, and recognize coins.", bullets: ["Use longer and shorter to compare length.", "A clock describes when something happens.", "Count coins by their values."], example: "Two nickels equal one dime: 5¢ + 5¢ = 10¢." }, mathQuestions: [q("Which is longer?", "Compare the objects.", ["a pencil", "a school bus", "They are always equal"], 1, "A school bus is longer than a pencil."), q("How many pennies make 5 cents?", "Each penny is 1 cent.", ["2", "5", "10"], 1, "Five 1-cent pennies make 5 cents."), q("What time is it when the short hand points to 3 and the long hand to 12?", "The long hand at 12 means o'clock.", ["3:00", "12:03", "6:00"], 0, "The hour hand is on 3 and the minute hand is on 12: 3:00.")], englishQuestions: [q("Which word names a feeling?", "Feelings happen inside us.", ["happy", "table", "jump"], 0, "Happy names a feeling."), q("Which is a complete message?", "Choose the complete thought.", ["Please pass the blue crayon.", "Blue crayon.", "Pass."], 0, "A clear sentence tells the reader the full idea."), q("What should you do when someone is speaking?", "Think about listening.", ["Listen and wait your turn.", "Shout over them.", "Walk away every time."], 0, "Listening and waiting your turn helps communication.")] },
  { title: "Story Garden", subtitle: "Retell a story and name the characters", color: "mint", icon: "✦", content: { intro: "Stories have characters, settings, and events. Readers retell important parts in order.", bullets: ["Who is in the story?", "Where and when does it happen?", "What happens first, next, and last?"], story: "Ben planted a bean seed in a small pot. He watered it every day. First a green sprout appeared, and later a tall plant grew two leaves.", example: "Ben planted and cared for a bean seed until it grew." }, mathQuestions: [q("You have 8 apples and give away 3. How many remain?", "Take 3 away from 8.", ["5", "6", "11"], 0, "8 − 3 = 5 apples remain."), q("Which shape has 4 equal sides?", "Think of a common 2-D shape.", ["square", "triangle", "circle"], 0, "A square has 4 equal sides."), q("What should you do when a problem feels hard?", "Think like a learner.", ["Try a drawing or another strategy.", "Give up immediately.", "Hide the problem."], 0, "A new representation or strategy can help you keep going.")], englishQuestions: [q("Who planted the seed?", "Look for the character.", ["Ben", "Mia", "A neighbour"], 0, "Ben planted the bean seed."), q("What happened first?", "Put the events in order.", ["A tall plant grew.", "Ben planted a seed.", "The leaves fell."], 1, "Planting the seed happened first."), q("What did Ben do each day?", "Find the repeated action.", ["He watered the seed.", "He moved the pot.", "He painted the leaves."], 0, "Ben watered it every day.")] },
];

const gradeThreeUnits: Unit[] = [
  { title: "Number Builder Bay", subtitle: "Place value, addition, subtraction, and rounding to 1,000", color: "coral", icon: "123", content: { intro: "Numbers help us plan, compare, and make choices. Build numbers from hundreds, tens, and ones, then use efficient strategies to add, subtract, and round.", bullets: ["Regroup when a place has more than 9.", "Round to the nearest ten or hundred to estimate.", "Check whether an answer makes sense."], example: "246 + 137 = 383: add ones, then tens, then hundreds." }, mathQuestions: [q("What is 246 + 137?", "Add ones, then tens, then hundreds.", ["373", "383", "393"], 1, "6 + 7 = 13; 4 + 3 + 1 = 8 tens; 2 + 1 = 3 hundreds. The answer is 383."), q("What is 500 − 268?", "Subtract 268 from 500 and regroup carefully.", ["232", "242", "332"], 0, "500 − 268 = 232. You can check by adding 232 + 268 to get 500."), q("What is 674 rounded to the nearest hundred?", "Look at the tens digit.", ["600", "700", "670"], 1, "The tens digit is 7, so 674 is closer to 700 than 600.")], englishQuestions: [q("Which sentence best summarizes a text about planning a fair school garden?", "Choose the big idea supported by details.", ["Students plan a garden by measuring, budgeting, and sharing jobs.", "The garden has a green sign.", "Someone used a shovel."], 0, "The first choice includes the main idea and the important supporting actions."), q("Which detail is strongest evidence?", "Evidence comes directly from the text.", ["The plan lists the cost of soil and seeds.", "Gardens are always fun.", "The writer probably likes plants."], 0, "A listed cost is a specific detail that supports the idea of budgeting."), q("Which revision adds a precise detail?", "Replace vague words with vivid, exact language.", ["The bird moved.", "The red cardinal darted between the maple branches.", "It was nice."], 1, "Darted, cardinal, maple, and branches help the reader picture the scene.")] },
  { title: "Multiplication Mountain", subtitle: "Multiplication, division, patterns, and problem solving", color: "blue", icon: "×", content: { intro: "Multiplication is a fast way to describe equal groups. Division helps us share fairly, and patterns help us predict what comes next.", bullets: ["An array shows equal rows and columns.", "Multiplication and division are related facts.", "Explain why your strategy works, not just the answer."], example: "4 × 6 means 4 equal groups of 6, or 6 + 6 + 6 + 6." }, mathQuestions: [q("What is 6 × 4?", "Think of six groups of four.", ["10", "20", "24"], 2, "6 groups of 4 equals 24."), q("A class shares 32 stickers equally among 4 teams. How many per team?", "Use a related division fact.", ["6", "8", "12"], 1, "32 ÷ 4 = 8 because 4 × 8 = 32."), q("What comes next: 5, 10, 15, 20, …?", "Look at the amount added each time.", ["21", "24", "25"], 2, "The pattern increases by 5, so 20 + 5 = 25.")], englishQuestions: [q("What does the word equal mean in a fair-share problem?", "Use the context of sharing.", ["The same amount for each person", "The biggest amount", "A surprise amount"], 0, "Equal shares give each person the same amount."), q("What is the main idea of a story about a team solving a tricky puzzle?", "Name the important message.", ["The team uses different strategies and keeps trying.", "The puzzle is blue.", "One child has a pencil."], 0, "The first choice describes the central action and lesson."), q("Which transition shows what happened next?", "Transitions help readers follow order.", ["Next", "Because", "Although"], 0, "Next signals the following event.")] },
  { title: "Fraction Forest", subtitle: "Fractions, geometry, measurement, and data", color: "mint", icon: "½", content: { intro: "Fractions describe equal parts, while geometry and data help us describe spaces and make decisions. Use models before rules.", bullets: ["The denominator names the equal parts in the whole.", "A numerator names how many parts we have.", "A graph gives evidence for a comparison."], example: "3/4 means 3 of 4 equal parts. Three quarters is greater than one quarter." }, mathQuestions: [q("Which fraction shows one part out of three equal parts?", "The denominator tells how many equal parts.", ["3/1", "1/2", "1/3"], 2, "1/3 means one of three equal parts."), q("Which fraction is greater: 1/2 or 1/4?", "Compare equal-sized wholes.", ["1/2", "1/4", "They are always equal"], 0, "One half is two quarters, so 1/2 is greater than 1/4."), q("A rectangle is 6 m long and 4 m wide. What is its area?", "Area = length × width.", ["10 m²", "20 m²", "24 m²"], 2, "6 × 4 = 24 square metres.")], englishQuestions: [q("What can you infer when a character packs an umbrella and boots?", "Use clues to make a reasonable idea.", ["Rain may be expected.", "It is definitely snowing.", "The character is going swimming."], 0, "An umbrella and boots are clues that rain may be expected."), q("Which sentence uses a vivid verb?", "Choose the action that helps you see it.", ["The cat went across the yard.", "The cat sprinted across the yard.", "The cat was there."], 1, "Sprinted gives a clear picture of fast movement."), q("Which title best fits a story about fixing a failed bridge model?", "Choose the title that hints at the central idea.", ["Try, Fix, Try Again", "The Blue Table", "A Random Tuesday"], 0, "The first title reflects the story's problem-solving message.")] },
  { title: "City Story Studio", subtitle: "Reading comprehension, paragraph writing, vocabulary, and media", color: "violet", icon: "Aa", content: { intro: "Readers ask questions, writers organize ideas, and media users notice who made a message and why. These skills help you navigate school and everyday life.", bullets: ["Use beginning, middle, and end to organize a narrative.", "Support an opinion with reasons and evidence.", "Ask who made a message and what they want you to do."], story: "Lena wanted to build a tiny bridge for the neighbourhood book swap. Her first design bent under ten books. She measured the cardboard again, folded two support beams, and tried a wider base. On fair day, the bridge held ten books. Lena smiled because the failed first attempt had taught her what to fix.", example: "A strong paragraph has a topic sentence, supporting details, and an ending." }, mathQuestions: [q("A $5 book costs $3. How much change do you receive?", "Subtract the cost from the amount paid.", ["$1", "$2", "$3"], 1, "$5 − $3 = $2 change."), q("A survey shows 8 children choose biking and 5 choose walking. How many more chose biking?", "Compare the two amounts.", ["2", "3", "4"], 1, "8 − 5 = 3, so 3 more children chose biking."), q("What is 3 × 4?", "Count 3 groups of 4.", ["7", "8", "12"], 2, "3 groups of 4 equals 12.")], englishQuestions: [q("What is the main idea of Lena's story?", "Choose the message supported by the whole story.", ["Trying, measuring, and revising helped Lena solve a problem.", "The bridge was made of blue cardboard.", "Fair day happened in the morning."], 0, "The first choice includes the problem, actions, and outcome."), q("Which detail proves the bridge was successful?", "Find what happened at the end.", ["It held ten books.", "Lena wanted a bridge.", "She had cardboard."], 0, "Holding ten books is evidence that the revised bridge worked."), q("Which sentence is the strongest topic sentence for a paragraph about revising?", "A topic sentence tells the paragraph's focus.", ["Revising helps writers and designers improve their work.", "I have a pencil.", "Things happen."], 0, "The first sentence clearly states the paragraph's focus.")] },
];

const genericUnitData: Record<2 | 4 | 5, string[][]> = {
  2: [["Place Value Port", "numbers to 1,000", "Build hundreds, tens, and ones for shopping and collecting.", "Math Market"], ["Addition Avenue", "addition and subtraction within 1,000", "Plan a class trip by adding people and subtracting what leaves.", "Trip Planner"], ["Arrays Arcade", "multiplication, division, and equal groups", "Share snacks fairly and use arrays to spot patterns.", "Fair Share"], ["Fraction Fair", "fractions, money, and measurement", "Compare halves, quarters, coins, and lengths.", "Fair Booth"]],
  4: [["Big Number Base", "numbers to 10,000 and multi-digit operations", "Use place value to plan a neighbourhood event budget.", "Budget Builder"], ["Factor Forest", "multiplication, division, and patterns", "Use factors and arrays to design garden plots.", "Garden Grid"], ["Fraction Falls", "fractions, decimals, and equivalent representations", "Compare recipe amounts and fair shares.", "Recipe Rescue"], ["Data District", "data, probability, and geometry", "Read a transit survey and design a park layout.", "City Data Lab"]],
  5: [["Decimal Dock", "whole numbers, decimals, and operations", "Compare prices, discounts, and savings in a pretend shop.", "Smart Shopper"], ["Fraction Foundry", "fractions, decimals, and proportional thinking", "Scale a recipe and share a class fundraiser fairly.", "Recipe Scale"], ["Shape & Space Studio", "measurement, area, perimeter, and angles", "Design a bedroom or community garden to scale.", "Design Lab"], ["Data & Decisions", "data, probability, and financial literacy", "Read graphs, make predictions, and build a simple budget.", "Decision Desk"]],
};

function makeQuestions(grade: 2 | 4 | 5, index: number): { math: Question[]; english: Question[] } {
  const math = grade === 2 ? [q("Which number has 6 hundreds, 2 tens, and 4 ones?", "Read hundreds, tens, ones.", ["624", "642", "264"], 0, "6 hundreds + 2 tens + 4 ones = 624."), q("What is 38 + 27?", "Add ones, then tens.", ["55", "65", "75"], 1, "8 + 7 = 15; regroup one ten. The answer is 65."), q("Which shows 3 groups of 4?", "Use repeated addition.", ["4 + 4 + 4", "3 + 4", "4 + 3"], 0, "3 groups of 4 is 4 + 4 + 4.")] : grade === 4 ? [q("What is 2,406 + 1,578?", "Add from ones to thousands and regroup.", ["3,984", "4,084", "3,874"], 0, "2,406 + 1,578 = 3,984."), q("Which is 4 × 25?", "Use 25 + 25 + 25 + 25.", ["75", "100", "125"], 1, "Four groups of 25 make 100."), q("What is the area of a 6 by 4 rectangle?", "Area = length × width.", ["10", "20", "24"], 2, "6 × 4 = 24 square units.")] : [q("What is 3.5 + 1.75?", "Line up decimal points.", ["4.25", "5.25", "5.75"], 1, "3.50 + 1.75 = 5.25."), q("Which fraction equals 0.75?", "Think in quarters.", ["1/4", "2/4", "3/4"], 2, "Three quarters is 0.75."), q("A rectangle is 8 m by 5 m. What is its perimeter?", "Add all four sides.", ["13 m", "26 m", "40 m"], 1, "8 + 5 + 8 + 5 = 26 m.")];
  const english = [q("What is the main idea of a text?", "Find the big message, not a tiny detail.", ["The main message", "The title only", "A random detail"], 0, "The main idea is the message that most details support."), q("Which detail is evidence?", "Evidence proves an idea.", ["A precise action from the text", "A guess unrelated to the text", "A favourite colour"], 0, "A precise detail from the text supports an answer."), q("Which revision makes writing clearer?", "Look for precise, connected words.", ["It was good.", "The bright kite tugged against the windy string.", "It happened."], 1, "Specific verbs and details help readers picture the idea.")];
  if (grade === 2 && index === 3) english[0] = q("Which fraction of a pizza is one half?", "Two equal parts make a whole.", ["1/2", "1/4", "2/3"], 0, "One of two equal parts is one half.");
  return { math, english };
}

function makeUnit(grade: 2 | 4 | 5, data: string[], index: number): Unit {
  const [title, subtitle, intro, gameName] = data; const questions = makeQuestions(grade, index);
  const content: LearningContent = { intro: `${intro} This unit connects ${subtitle} to a real-world challenge: ${gameName}.`, bullets: ["Learn the idea with a worked example.", "Use it in a game connected to everyday life.", "Explain your choice and check your work."], example: `Real-world challenge: ${gameName}. A careful plan helps you make a better decision.`, gamePrompt: `In ${gameName}, which strategy helps you most?`, gameOptions: ["Draw a model and label it", "Guess quickly", "Ignore the units"], gameAnswer: 0 };
  return { title, subtitle, color: index % 2 ? "blue" : "coral", icon: index % 2 ? "✦" : "▣", content, mathQuestions: questions.math, englishQuestions: questions.english };
}

function unitsFor(grade: Grade): Unit[] { if (grade === 1) return gradeOneUnits; if (grade === 3) return gradeThreeUnits; return genericUnitData[grade].map((data, index) => makeUnit(grade, data, index)); }

export function getProgram(grade: Grade): CurriculumProgram {
  const units = unitsFor(grade);
  const activities: Activity[] = units.flatMap((unit, index) => {
    const week = index * 2 + 1; const story = unit.content.story ?? `The class took on a ${unit.title.toLowerCase()} challenge. They gathered clues, compared choices, and explained their final decision in a short paragraph.`;
    const lesson: Activity = { id: `${grade}-u${index}-lesson`, week, title: `${unit.title} Story Studio`, subtitle: `Learn ${unit.subtitle} through a story`, subject: "english", kind: "lesson", minutes: 12, xp: 80, color: "violet", icon: "Aa", questions: unit.englishQuestions, content: { ...unit.content, story } };
    const game: Activity = { id: `${grade}-u${index}-game`, week, title: `${unit.title} Challenge`, subtitle: unit.subtitle, subject: "math", kind: "game", minutes: 12, xp: 90, color: unit.color, icon: unit.icon, questions: unit.mathQuestions, content: unit.content };
    const quiz: Activity = { id: `${grade}-u${index}-quiz`, week: week + 1, title: `${unit.title} Quick Checks`, subtitle: "Short practice checkpoints", subject: "math", kind: "quiz", minutes: 8, xp: 70, color: "gold", icon: "?", questions: unit.mathQuestions.slice(0, 2), content: unit.content };
    const test: Activity = { id: `${grade}-u${index}-test`, week: week + 1, title: `${unit.title} Unit Quest`, subtitle: "Pass the unit test to unlock the next chapter", subject: "math", kind: "test", minutes: 15, xp: 140, color: "mint", icon: "★", questions: [...unit.mathQuestions, ...unit.englishQuestions.slice(0, 1)], content: unit.content };
    return [lesson, game, quiz, test];
  });
  const weeks: Week[] = units.map((unit, index) => ({ id: index + 1, label: `UNIT ${index + 1}`, title: unit.title, detail: `${unit.subtitle} · content, game, quick checks, then a unit quest`, color: unit.color, ids: activities.filter((item) => item.id.startsWith(`${grade}-u${index}-`)).map((item) => item.id) }));
  return { grade, activities, weeks, contentFor: (activity) => activity.content };
}

export function getGradeLabel(grade: Grade): string { return `Grade ${grade}`; }
