import type { Grade, Question } from "./curriculum";

const q = (prompt: string, hint: string, options: string[], answer: number, explanation: string): Question => ({ prompt, hint, options, answer, explanation });

const diagnosticByGrade: Record<Grade, Question[]> = {
  1: [
    q("What number comes after 9?", "Count one more.", ["8", "10", "19", "90"], 1, "Counting one more after 9 gives 10."),
    q("What is 5 + 2?", "Put the two groups together.", ["6", "7", "8", "10"], 1, "Five plus two is seven."),
    q("What is 8 − 3?", "Take away three from eight.", ["5", "6", "11", "4"], 0, "Eight take away three leaves five."),
    q("Which group has more?", "Compare the amounts.", ["6 apples", "4 apples", "They are equal", "0 apples"], 0, "Six is greater than four, so six apples is the larger group."),
    q("Which shape has three straight sides?", "Count the sides.", ["Circle", "Triangle", "Square", "Rectangle"], 1, "A triangle has three straight sides."),
    q("What time is shown when the short hand points to 3 and the long hand points to 12?", "The long hand at 12 means exactly on the hour.", ["3:00", "12:03", "6:00", "3:12"], 0, "The hour hand is on 3 and the minute hand is on 12, so the time is 3:00."),
    q("How much is one penny worth?", "Think about Canadian coins.", ["1¢", "5¢", "10¢", "25¢"], 0, "A Canadian penny represents one cent, even though pennies are no longer used in everyday Canadian cash transactions."),
    q("What comes next: 2, 4, 6, …?", "Look at how much the numbers grow.", ["7", "9", "8", "10"], 2, "The pattern adds two each time, so six plus two is eight."),
    q("Which number is greater?", "Compare the tens first.", ["12", "21", "11", "2"], 1, "Twenty-one has two tens; twelve has one ten, so 21 is greater."),
    q("Which number is one ten and three ones?", "Build the number from tens and ones.", ["13", "31", "10", "4"], 0, "One ten is 10 and three ones make 13."),
    q("Which word begins with the /s/ sound?", "Say each word slowly.", ["sun", "map", "dog", "fish"], 0, "Sun begins with the /s/ sound."),
    q("Which word rhymes with cat?", "Listen to the ending sound.", ["sun", "hat", "dog", "bed"], 1, "Cat and hat end with the same sound."),
    q("Which sentence is written correctly?", "Check the capital letter and ending mark.", ["the dog ran", "The dog ran.", "the Dog ran.", "The dog ran"], 1, "A sentence begins with a capital letter and ends with punctuation."),
    q("Mia puts on boots and carries an umbrella before going outside. What can you infer?", "Use clues to make a sensible idea.", ["It may rain.", "It is definitely hot.", "She is going swimming.", "It is midnight."], 0, "Boots and an umbrella are clues that rain may be expected."),
    q("Which word names a person, place, animal, or thing?", "Look for a naming word.", ["run", "apple", "quickly", "bright"], 1, "Apple names a thing, so it is a naming word."),
    q("Which word shows an action?", "A verb tells what someone or something does.", ["jump", "blue", "pencil", "quiet"], 0, "Jump tells about an action."),
    q("Tom planted a seed, watered it, and watched a sprout grow. What happened first?", "Find the first event.", ["Tom planted a seed.", "A sprout grew.", "Tom picked a flower.", "The seed disappeared."], 0, "Planting the seed is the first event in the sequence."),
    q("A text explains how to care for a kitten. What is its main idea?", "Choose the big message, not one small detail.", ["How to care for a kitten", "The kitten is white", "The kitten has a name", "Someone bought food"], 0, "The main idea is the overall message the details explain."),
    q("Which sentence needs a question mark?", "Look for a question.", ["Please sit down.", "Where is my hat", "The hat is blue.", "I found it."], 1, "Where is my hat is a question, so it needs a question mark."),
    q("Which word means more than one cat?", "Look for the plural ending.", ["cat", "cat's", "cats", "catting"], 2, "Cats means more than one cat."),
  ],
  2: [
    q("Which number has 6 hundreds, 2 tens, and 4 ones?", "Read the hundreds, tens, and ones places.", ["624", "642", "264", "604"], 0, "Six hundreds, two tens, and four ones make 624."),
    q("What is 38 + 27?", "Add ones, regroup, then add tens.", ["55", "65", "75", "61"], 1, "Eight plus seven is 15; one ten is regrouped. Three tens plus two tens plus one ten is six tens, so the answer is 65."),
    q("What is 72 − 38?", "Regroup one ten before subtracting.", ["34", "44", "40", "30"], 0, "72 − 38 = 34. Check by adding 34 + 38 to get 72."),
    q("Which shows 3 groups of 4?", "Use repeated addition.", ["4 + 4 + 4", "3 + 4", "4 + 3", "3 + 3 + 3"], 0, "Three groups of four are 4 + 4 + 4, which equals 12."),
    q("Twelve stickers are shared equally among three children. How many does each child get?", "Think of 12 divided into three equal groups.", ["3", "4", "6", "9"], 1, "12 divided into three equal groups gives four in each group."),
    q("What is half of 8?", "Split eight into two equal groups.", ["2", "4", "6", "16"], 1, "Eight split into two equal groups gives four in each group."),
    q("What time is one hour after 2:00?", "Move the hour hand forward once.", ["1:00", "2:30", "3:00", "4:00"], 2, "One hour after 2:00 is 3:00."),
    q("Which Canadian coin is worth 25 cents?", "Think of the coin called a quarter.", ["Nickel", "Dime", "Quarter", "Loonie"], 2, "A quarter is worth 25 cents."),
    q("A rectangle has four sides of 4 cm each. What is its perimeter?", "Add all four sides.", ["8 cm", "12 cm", "16 cm", "20 cm"], 2, "4 + 4 + 4 + 4 = 16 cm."),
    q("What comes next: 5, 10, 15, …?", "Find the amount added each time.", ["18", "20", "25", "30"], 1, "The pattern adds five, so 15 + 5 = 20."),
    q("A story says, ‘Nora packed a lunch, checked the map, and walked to the park.’ What did Nora do second?", "Put the events in order.", ["Packed a lunch", "Checked the map", "Walked home", "Bought a bike"], 1, "Checking the map is the second event stated."),
    q("What is the main idea of a text about planting a community garden?", "Choose what the whole text is mostly about.", ["Neighbours plan and care for a garden together.", "The sign is green.", "One person wore boots.", "There was one shovel."], 0, "The first choice includes the central action supported by the details."),
    q("Which word is closest in meaning to enormous?", "Use the surrounding idea of size.", ["tiny", "huge", "quiet", "smooth"], 1, "Enormous means very large, or huge."),
    q("Which sentence uses a describing word?", "A describing word tells more about a noun.", ["The bright kite flew.", "The kite flew.", "Fly the kite.", "Kite."], 0, "Bright describes the kite."),
    q("Which detail is evidence that a character is prepared for rain?", "Find a detail that proves the idea.", ["The character carries an umbrella.", "The character likes music.", "The character has a red hat.", "The character is hungry."], 0, "Carrying an umbrella directly supports the idea that the character is ready for rain."),
    q("Which is an opinion?", "An opinion is a belief that people may disagree about.", ["A week has seven days.", "A triangle has three sides.", "The best playground is the one with the big slide.", "April comes after March."], 2, "The best playground is a personal judgement, so it is an opinion."),
    q("Which sentence is punctuated correctly?", "Check the comma in the greeting.", ["Hi Sam can you help?", "Hi, Sam. Can you help?", "Hi Sam, Can you help", "hi, Sam can you help."], 1, "The greeting uses a comma and the question ends with a question mark."),
    q("What does the prefix un- often mean?", "Try it in unhappy or unsafe.", ["again", "not", "small", "before"], 1, "The prefix un- often means not."),
    q("Which sentence would best end a paragraph about saving water?", "Choose an ending that brings the idea together.", ["That is why small water-saving choices matter.", "My shoes are blue.", "Then I saw a cloud.", "Water is a word."], 0, "The first sentence wraps up the paragraph's topic."),
    q("A poster says ‘Bring a reusable bottle!’ Who is the message trying to reach?", "Think about who might act on the message.", ["People who can bring a bottle", "Only astronauts", "Nobody", "The weather"], 0, "The poster is addressing people who can choose a reusable bottle."),
  ],
  3: [
    q("What is 246 + 137?", "Add ones, then tens, then hundreds.", ["373", "383", "393", "483"], 1, "6 + 7 = 13; regroup one ten. Then 4 + 3 + 1 = 8 tens and 2 + 1 = 3 hundreds, making 383."),
    q("What is 500 − 268?", "Regroup carefully across the zeros.", ["232", "242", "332", "368"], 0, "500 − 268 = 232. Check by adding 232 + 268 to get 500."),
    q("What is 674 rounded to the nearest hundred?", "Look at the tens digit.", ["600", "700", "670", "680"], 1, "The tens digit is 7, so 674 is closer to 700 than 600."),
    q("What is 6 × 4?", "Think of six equal groups of four.", ["10", "20", "24", "28"], 2, "Six groups of four equal 24."),
    q("Thirty-two stickers are shared equally among four teams. How many per team?", "Use a related multiplication fact.", ["6", "8", "12", "16"], 1, "32 ÷ 4 = 8 because 4 × 8 = 32."),
    q("Which fraction is greater?", "Compare equal-sized wholes.", ["1/2", "1/4", "They are equal", "0/4"], 0, "One half is two quarters, so 1/2 is greater than 1/4."),
    q("A rectangle is 6 m long and 4 m wide. What is its area?", "Area is length multiplied by width.", ["10 m²", "20 m²", "24 m²", "28 m²"], 2, "6 × 4 = 24 square metres."),
    q("What comes next: 5, 10, 15, 20, …?", "Find the constant change.", ["21", "24", "25", "30"], 2, "The pattern increases by five, so 20 + 5 = 25."),
    q("A $5 book costs $3. How much change do you receive?", "Subtract the cost from the amount paid.", ["$1", "$2", "$3", "$8"], 1, "$5 − $3 = $2 change."),
    q("What is 3/4?", "The denominator names equal parts; the numerator names parts chosen.", ["3 of 4 equal parts", "4 of 3 equal parts", "3 whole groups", "1 of 4 parts"], 0, "3/4 means three of four equal parts."),
    q("What is the main idea of a text about planning a fair school garden?", "Choose the big idea supported by details.", ["Students plan a garden by measuring, budgeting, and sharing jobs.", "The garden has a green sign.", "Someone used a shovel.", "The soil was dark."], 0, "The first choice includes the important actions and central message."),
    q("Which detail is strongest evidence that a plan uses a budget?", "Evidence comes directly from the text.", ["The plan lists the cost of soil and seeds.", "Gardens are always fun.", "The writer probably likes plants.", "The garden is outside."], 0, "Listed costs are specific evidence of budgeting."),
    q("Which revision adds a precise detail?", "Replace vague words with exact language.", ["The bird moved.", "The red cardinal darted between the maple branches.", "It was nice.", "Something happened."], 1, "The precise nouns and vivid verb help the reader picture the scene."),
    q("What can you infer when a character packs boots and an umbrella?", "Use more than one clue.", ["Rain may be expected.", "The character is definitely swimming.", "It is a snowstorm for sure.", "The character is indoors."], 0, "Boots and an umbrella together suggest rain may be expected."),
    q("Which transition shows what happened next?", "Transitions help readers follow order.", ["Next", "Because", "Although", "Instead"], 0, "Next signals the following event."),
    q("Which is the strongest topic sentence for a paragraph about revising?", "A topic sentence tells the paragraph's focus.", ["Revising helps writers and designers improve their work.", "I have a pencil.", "Things happen.", "The table is brown."], 0, "The first sentence clearly states the paragraph's focus."),
    q("Which source is most likely written to persuade you to recycle?", "Think about the author's purpose.", ["A poster saying ‘Recycle today!’", "A dictionary entry for recycle", "A weather chart", "A recipe for soup"], 0, "A call to action on a poster is meant to persuade people to act."),
    q("Which sentence uses a conjunction to connect two ideas?", "Look for a joining word.", ["I packed a snack and a map.", "The bright kite.", "Running quickly.", "The park."], 0, "And joins the two things packed."),
    q("Which detail would best support the idea that a bridge design is strong?", "Choose proof of the claim.", ["It held ten books without bending.", "It was made on Tuesday.", "The table was nearby.", "The builder wore a hat."], 0, "Holding ten books without bending directly shows strength."),
    q("What should a summary include?", "A summary is short but complete.", ["The most important ideas and events", "Every tiny detail", "Only your opinion", "A new ending"], 0, "A summary keeps the important ideas and events without every small detail."),
  ],
  4: [
    q("What is 2,406 + 1,578?", "Add from ones to thousands and regroup.", ["3,984", "4,084", "3,874", "4,984"], 0, "2,406 + 1,578 = 3,984."),
    q("Which is 4 × 25?", "Use four groups of 25.", ["75", "100", "125", "150"], 1, "25 + 25 + 25 + 25 = 100."),
    q("What is the area of a 6 by 4 rectangle?", "Area equals length times width.", ["10", "20", "24", "28"], 2, "6 × 4 = 24 square units."),
    q("Which number is a factor of 36?", "A factor divides the number evenly.", ["5", "7", "9", "11"], 2, "36 ÷ 9 = 4, so 9 is a factor of 36."),
    q("What is 3/4 written as a decimal?", "Divide three by four or think of quarters.", ["0.25", "0.34", "0.75", "3.4"], 2, "Three quarters is 0.75."),
    q("What is 3.5 + 1.75?", "Line up the decimal points.", ["4.25", "5.25", "5.75", "6.25"], 1, "3.50 + 1.75 = 5.25."),
    q("A rectangle is 8 m by 5 m. What is its perimeter?", "Add all four sides.", ["13 m", "26 m", "40 m", "20 m"], 1, "8 + 5 + 8 + 5 = 26 m."),
    q("A bag has 3 red, 2 blue, and 5 green marbles. Which colour is most likely to be picked?", "Compare the counts.", ["Red", "Blue", "Green", "All are equally likely"], 2, "Green has the greatest count, so it is most likely."),
    q("What is 4,000 − 1,876?", "Regroup across the zeros.", ["2,124", "2,224", "3,124", "2,876"], 0, "4,000 − 1,876 = 2,124."),
    q("Which angle is closest to a right angle?", "A right angle is 90 degrees.", ["20°", "45°", "90°", "180°"], 2, "A right angle measures 90 degrees."),
    q("What is the main idea of a text comparing two ways to save energy?", "Find the message supported by both sections.", ["Different choices can reduce energy use.", "One light bulb is yellow.", "The text has two headings.", "Someone opened a window."], 0, "The first choice expresses the central idea of the comparison."),
    q("Which detail is evidence that a claim is reliable?", "Look for a specific source or measurement.", ["The claim includes results from a recorded survey.", "The writer says ‘trust me.’", "The sentence uses a big word.", "The page is colourful."], 0, "Recorded survey results provide specific evidence."),
    q("Which sentence combines ideas most clearly?", "Use a joining word and precise ideas.", ["The river rose, so the town opened the flood gates.", "River. Gates. Town.", "The town river.", "It happened."], 0, "So clearly shows the connection between the rising river and the response."),
    q("What does the prefix re- mean in rebuild?", "Try the word rebuild in a sentence.", ["again", "not", "under", "before"], 0, "Rebuild means build again."),
    q("Which point of view uses I and we?", "Look at the narrator's words.", ["First person", "Second person", "Third person", "No point of view"], 0, "First-person narrators use I or we."),
    q("Which statement is a fact?", "A fact can be checked.", ["Ottawa is Canada's capital city.", "Ottawa is the most exciting city.", "Every park is perfect.", "Blue is the best colour."], 0, "Canada's capital city is a checkable fact."),
    q("Which detail would best support an opinion that a park is accessible?", "Choose evidence about access.", ["It has a ramp and clear paths.", "It has a red sign.", "It opened on Tuesday.", "The grass is green."], 0, "A ramp and clear paths are direct evidence of accessibility."),
    q("What is a good first step when evaluating an online message?", "Ask about the message before believing it.", ["Check who created it and why.", "Share it immediately.", "Trust the picture alone.", "Ignore every source."], 0, "Creator and purpose are important clues when evaluating a message."),
    q("Which sentence best concludes a paragraph about reducing waste?", "Bring the key idea together.", ["Small repeated choices can reduce the waste a community sends to landfill.", "My backpack is green.", "Waste is a short word.", "Then I ate lunch."], 0, "The first sentence gives a clear conclusion connected to the topic."),
    q("What does a summary leave out?", "A summary is shorter than the original.", ["Unimportant small details", "The central idea", "Major events", "Important evidence"], 0, "A summary keeps the important ideas and leaves out minor details."),
  ],
  5: [
    q("What is 3.5 + 1.75?", "Write 3.5 as 3.50 first.", ["4.25", "5.25", "5.75", "6.25"], 1, "3.50 + 1.75 = 5.25."),
    q("Which fraction equals 0.75?", "Think in quarters.", ["1/4", "2/4", "3/4", "4/5"], 2, "Three quarters is 0.75."),
    q("A rectangle is 8 m by 5 m. What is its perimeter?", "Add all four sides.", ["13 m", "26 m", "40 m", "80 m"], 1, "8 + 5 + 8 + 5 = 26 m."),
    q("What is 15% of 200?", "Find 10% and 5%, then combine them.", ["15", "20", "30", "40"], 2, "10% of 200 is 20 and 5% is 10, so 15% is 30."),
    q("Which ratio is equivalent to 2:3?", "Multiply both parts by the same number.", ["3:4", "4:6", "5:6", "6:8"], 1, "2:3 multiplied by two is 4:6."),
    q("A $40 jacket is 25% off. How much is the discount?", "Find one quarter of $40.", ["$5", "$10", "$15", "$25"], 1, "25% is one quarter; one quarter of $40 is $10."),
    q("What is the volume of a rectangular prism that is 3 × 4 × 5 units?", "Multiply length, width, and height.", ["12", "20", "60", "120"], 2, "3 × 4 × 5 = 60 cubic units."),
    q("A bag has 2 red and 8 blue marbles. What is the probability of picking red?", "Compare red marbles with all marbles.", ["1/2", "1/5", "2/8", "8/10"], 1, "There are 2 red out of 10 total, which simplifies to 1/5."),
    q("What is 4,500 ÷ 9?", "Use a related multiplication fact.", ["50", "500", "900", "4,491"], 1, "9 × 500 = 4,500, so the quotient is 500."),
    q("Which number is prime?", "A prime has exactly two factors.", ["21", "27", "29", "35"], 2, "29 has only 1 and 29 as factors, so it is prime."),
    q("What is the author's purpose in a text explaining how to spot a misleading advertisement?", "Ask what the author wants readers to do.", ["To inform readers and help them evaluate claims", "To tell a fictional adventure", "To list favourite colours", "To sell one specific toy"], 0, "The text teaches readers how to evaluate claims, so its purpose is to inform and equip them."),
    q("Which evidence best supports the claim that a source is trustworthy?", "Choose evidence about credibility.", ["It names its sources and explains how the data was collected.", "It uses lots of exclamation marks.", "It has a bright background.", "It makes the claim very quickly."], 0, "Named sources and a clear method help readers evaluate credibility."),
    q("Which sentence uses a semicolon correctly?", "A semicolon can join closely related complete thoughts.", ["The bus was late; we checked the schedule.", "The bus; was late.", "The bus was; late we checked.", "The; bus was late."], 0, "Both sides of the semicolon are complete, related thoughts."),
    q("What is a theme?", "Think about the lasting message of a story.", ["A lesson or message about life", "The list of characters only", "The page number", "The setting's weather"], 0, "A theme is a story's deeper message or lesson."),
    q("Which sentence best states an arguable claim about school gardens?", "A claim is a position that reasons can support.", ["School gardens should be used for science learning because students can observe real ecosystems.", "School gardens exist.", "A garden has soil.", "Plants need water."], 0, "The first sentence takes a position and gives a reason that can be supported."),
    q("Which detail is most relevant to an argument about public transit?", "Choose evidence connected to the claim.", ["A survey found that more riders used transit after service became more frequent.", "The bus was painted blue.", "A rider wore a yellow coat.", "The station had a clock."], 0, "The survey result directly relates service frequency to transit use."),
    q("What does a counterargument do?", "Think about how arguments become stronger.", ["It acknowledges a different point of view.", "It repeats the title.", "It removes all evidence.", "It changes the topic completely."], 0, "A counterargument recognizes another perspective before responding to it."),
    q("Which revision makes this sentence more precise: ‘The project was good.’", "Replace vague words with measurable details.", ["The project was good.", "The project reduced food waste by 18%.", "The project happened.", "The project was a thing."], 1, "The second sentence gives a specific, measurable result."),
    q("Which question should you ask before sharing a surprising online claim?", "Pause and verify.", ["Who made it, what evidence supports it, and when was it published?", "Does the picture look exciting?", "Did someone type it in capitals?", "Will it get many likes?"], 0, "Creator, evidence, and date are useful checks before sharing information."),
    q("What should a strong summary of an argument include?", "Keep the argument's structure.", ["The claim and the most important reasons or evidence", "Every sentence copied exactly", "Only whether you liked it", "A completely new opinion"], 0, "A strong summary preserves the claim and its key support without copying everything."),
  ],
};

export function getDiagnosticQuestions(grade: Grade): Question[] {
  return diagnosticByGrade[grade];
}
