import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createHash, randomBytes, randomUUID, timingSafeEqual } from "node:crypto";
import { Pool, type PoolClient } from "pg";

export const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: { rejectUnauthorized: false }, max: 5, connectionTimeoutMillis: 8000 });
export const emptyProgress = { xp: 0, stars: 0, coins: 25, streak: 0, completed: [], mastery: { math: 0, english: 0 }, attempts: {}, diagnosticComplete: false, diagnosticScore: 0, lastActivity: "", badges: [] };
export const defaultSettings = { breaks: true, dailyLimit: 90, subjects: "all" };
export function json(res: VercelResponse, status: number, body: unknown) { return res.status(status).setHeader("Content-Type", "application/json").json(body); }
export function method(req: VercelRequest, res: VercelResponse, expected: string) { if (req.method !== expected) { res.setHeader("Allow", expected); json(res, 405, { error: "Method not allowed." }); return false; } return true; }
export function normalizeEmail(value: unknown) { return typeof value === "string" ? value.trim().toLowerCase() : ""; }
export function validPassword(value: unknown): value is string { return typeof value === "string" && value.length >= 8 && /[A-Za-z]/.test(value) && /\d/.test(value); }
export function validGrade(value: unknown) { return [1, 2, 3, 4, 5].includes(Number(value)); }
export async function hashPassword(value: string) { const salt = randomBytes(16); const derived = await new Promise<Buffer>((resolve, reject) => { import("node:crypto").then(({ scrypt }) => scrypt(value, salt, 64, (error, key) => error ? reject(error) : resolve(key as Buffer))); }); return `scrypt:${salt.toString("hex")}:${derived.toString("hex")}`; }
export async function verifyPassword(value: unknown, stored: string) { if (typeof value !== "string") return false; const parts = stored.split(":"); if (parts[0] !== "scrypt" || !parts[1] || !parts[2]) return false; const salt = Buffer.from(parts[1], "hex"); const expected = Buffer.from(parts[2], "hex"); const actual = await new Promise<Buffer>((resolve, reject) => { import("node:crypto").then(({ scrypt }) => scrypt(value, salt, expected.length, (error, key) => error ? reject(error) : resolve(key as Buffer))); }); return actual.length === expected.length && timingSafeEqual(actual, expected); }
function cookieOptions(maxAge: number) { return `Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`; }
export async function createSession(client: PoolClient, accountId: string, res: VercelResponse) { const token = randomBytes(32).toString("base64url"); const tokenHash = createHash("sha256").update(token).digest("hex"); await client.query("INSERT INTO sessions (token_hash, account_id, expires_at) VALUES ($1, $2, now() + interval '30 days')", [tokenHash, accountId]); res.setHeader("Set-Cookie", `brighttrail_session=${token}; ${cookieOptions(60 * 60 * 24 * 30)}`); }
function sessionToken(req: VercelRequest) { const raw = req.headers.cookie ?? ""; const pair = raw.split(";").map((item) => item.trim()).find((item) => item.startsWith("brighttrail_session=")); return pair?.slice("brighttrail_session=".length) ?? ""; }
export async function clearSession(req: VercelRequest, res: VercelResponse) { const token = sessionToken(req); if (token) await pool.query("DELETE FROM sessions WHERE token_hash = $1", [createHash("sha256").update(token).digest("hex")]); res.setHeader("Set-Cookie", `brighttrail_session=; ${cookieOptions(0)}`); }
export async function sessionPayload(req: VercelRequest) { const token = sessionToken(req); if (!token) return null; const tokenHash = createHash("sha256").update(token).digest("hex"); const result = await pool.query("SELECT l.id, l.name, l.avatar, l.grade, l.created_at, a.parent_email, s.progress, s.settings FROM sessions ss JOIN accounts a ON a.id = ss.account_id JOIN learners l ON l.account_id = a.id JOIN learner_state s ON s.learner_id = l.id WHERE ss.token_hash = $1 AND ss.expires_at > now() ORDER BY l.created_at LIMIT 1", [tokenHash]); if (!result.rowCount) return null; const row = result.rows[0]; return { profile: { id: row.id, name: row.name, avatar: row.avatar, grade: row.grade, createdAt: row.created_at, parentEmail: row.parent_email }, progress: row.progress, settings: row.settings }; }
export async function withTransaction<T>(fn: (client: PoolClient) => Promise<T>) { const client = await pool.connect(); try { await client.query("BEGIN"); const result = await fn(client); await client.query("COMMIT"); return result; } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); } }
